version: "3.1"
services:
  memos-bot:
    container_name: memos-bot
    image: memosbot
    build:
      context: .
      args:
        PUID: $PUID
        PGID: $PGID
        UNAME: memosuser
    restart: unless-stopped
    volumes:
      - ./db:/bot/db
